#!/system/bin/sh

PPPD_ARGS=`/system/bin/getprop ril.pppd_runner.args`

/system/bin/pppd $PPPD_ARGS defaultroute local usepeerdns \
    noipdefault unit 0 nodetach linkname gprs \
    lcp-restart 1 lcp-max-configure 3 ipcp-restart 1 ipcp-max-configure 3

